[features]
seeds = false
skip-lint = false

[programs.devnet]
moltlaunch = "6AZSAhq4iJTwCfGEVssoa1p3GnBqGkbcQ1iDdP1U1pSb"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "/home/clawd/moltbot-trial/products/launchpad/devnet-wallet.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
